.nh
.TH "gh" "1" "Jan 2021" "" ""

.SH NAME
.PP
gh\-pr\-checkout \- Check out a pull request in git


.SH SYNOPSIS
.PP
\fBgh pr checkout { |  | } [flags]\fP


.SH DESCRIPTION
.PP
Check out a pull request in git


.SH OPTIONS
.PP
\fB\-\-recurse\-submodules\fP[=false]
	Update all active submodules (recursively)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-pr(1)\fP
